/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessToken: () => import('#controllers/access_token_controller'),
  Assentos: () => import('#controllers/assentos_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Pagamentos: () => import('#controllers/pagamentos_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Viagems: () => import('#controllers/viagems_controller'),
}
