/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AssentoSchema extends BaseModel {
  static $columns = ['id', 'assento', 'viagemId'] as const
  $columns = AssentoSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare assento: string
  @column()
  declare viagemId: number | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['id', 'tokenableId', 'type', 'name', 'hash', 'abilities', 'createdAt', 'updatedAt', 'lastUsedAt', 'expiresAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column()
  declare name: string | null
  @column()
  declare hash: string
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
}

export class PagamentoSchema extends BaseModel {
  static $columns = ['id', 'metodo', 'codigo', 'qrcode', 'assentoId', 'userId', 'createdAt', 'updatedAt'] as const
  $columns = PagamentoSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare metodo: string
  @column()
  declare codigo: string
  @column()
  declare qrcode: string
  @column()
  declare assentoId: number | null
  @column()
  declare userId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['id', 'fullName', 'email', 'password', 'telefone', 'createdAt', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare fullName: string | null
  @column()
  declare email: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare telefone: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ViagemSchema extends BaseModel {
  static $columns = ['id', 'origem', 'destino', 'data', 'preco', 'createdAt', 'updatedAt'] as const
  $columns = ViagemSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare origem: string
  @column()
  declare destino: string
  @column()
  declare data: string
  @column()
  declare preco: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
